markdown: kramdown
defaults:
  -
    scope:
      path: "" # anywhere
    values:
      layout: default
collections:
  about:
    output: true
    permalink: /:collection/:slug
  albums:
    output: true
    permalink: /:collection/:slug
